### ISSUE TITLE
Undefined index: action

### ISSUE THREAD

**Issue by siebird** [mmikkel/limitblocktype#3]
Getting this error on password resets. Looks to be an issue with this plugin:

```
2017/03/13 14:12:02 [error] [php] Undefined index: action (../craft/plugins/limitblocktype/LimitBlockTypePlugin.php:50)
Stack trace:
#0 ../craft/app/etc/web/WebApp.php(257): Craft\PluginsService->loadPlugins()
#1 ../craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#2 ../craft/app/index.php(62): Craft\WebApp->run()
#3 ../public/index.php(19): require_once()
REQUEST_URI=/admin/actions/users/setpassword?code=Ve7vutyTg%7E31TgSoJitgZn4aMRZEtI8f&id=9362ecb4-62fc-4607-a1f9-18ad6228763f
```

which references this conditional `LimitBlockTypePlugin.php:50`: 

```
if (!empty($vars) && $vars['action'] === 'fields/saveField' && $vars['type'] === 'Matrix') {
  // This is so hacky I don't even
  craft()->runController('limitBlockType/saveField');
}
```

**Comment by achord** [comment]
I'm having this issue as well. It's interfering with new user password creation and saving Zenbu settings.

**Comment by achord** [comment]
It's also throwing an error on login:

```
Notice: Undefined index: action in /var/www/craft/plugins/limitblocktype/LimitBlockTypePlugin.php on line 50

Warning: Declaration of Craft\UserSessionService::login($username, $password, $rememberMe = false) should be compatible with CWebUser::login($identity, $duration = 0) in /var/www/craft/app/services/UserSessionService.php on line 17

Warning: Declaration of Craft\UserSessionService::afterLogin() should be compatible with CWebUser::afterLogin($fromCookie) in /var/www/craft/app/services/UserSessionService.php on line 17

Bad Request
The CSRF token could not be verified.
```

**Comment by danjrichardson** [comment]
I'm also having this issue with password resets, and also CSRF token. Both only happen sporadically

**Comment by joekromer** [comment]
I've started running into this problem just recently. Has anyone figured out a patch yet?

**Comment by siebird** [comment]
I disabled the plugin. No patch AFAIK

**Comment by mmikkel** [comment]
Fixed in https://github.com/mmikkel/limitblocktype/releases/tag/v.1.0.2
